name: todo_liste_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2

flutter:
  uses-material-design: true
